---
name: check-wip
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  pr-wip-check:
    runs-on: ubuntu-latest
    steps:
    - uses: tim-actions/wip-check@master
      with:
        labels: '["wip"]'
        keywords: '["WIP", "wip"]'
