---
name: prepublish-version
on:
  push:
    tags:
      - 'v*'
jobs:
  package-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - run: just package
  create-release:
    needs: package-binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
  publish-artifacts:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - arm
          - arm64
          - mips
          - mips64
    steps:
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./build/mcsm-linux-${{ matrix.architecture }}.tgz
          asset_name: build/mcsm-linux-${{ matrix.architecture }}.tgz
          asset_content_type: application/gzip
