---
name: run-tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - run: just test
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
          java-package: jre
      - run: echo "${GITHUB_WORKSPACE}/build" >> $GITHUB_PATH
      - run: just integration
